// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/admin_v1/admin.proto

package admin_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // all, active, suspended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUsersRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AdminUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ListUsersResponse) GetUsers() []*AdminUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // numeric ID or UUID
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	InsertedAt    string                 `protobuf:"bytes,6,opt,name=inserted_at,json=insertedAt,proto3" json:"inserted_at,omitempty"`
	IsKyc         bool                   `protobuf:"varint,7,opt,name=is_kyc,json=isKyc,proto3" json:"is_kyc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminUser) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AdminUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUser) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AdminUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminUser) GetInsertedAt() string {
	if x != nil {
		return x.InsertedAt
	}
	return ""
}

func (x *AdminUser) GetIsKyc() bool {
	if x != nil {
		return x.IsKyc
	}
	return false
}

type SuspendUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`           // e.g. "1_day", "1_week", "permanent"
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendUserRequest) Reset() {
	*x = SuspendUserRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendUserRequest) ProtoMessage() {}

func (x *SuspendUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendUserRequest.ProtoReflect.Descriptor instead.
func (*SuspendUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SuspendUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuspendUserRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *SuspendUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnsuspendUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsuspendUserRequest) Reset() {
	*x = UnsuspendUserRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsuspendUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsuspendUserRequest) ProtoMessage() {}

func (x *UnsuspendUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsuspendUserRequest.ProtoReflect.Descriptor instead.
func (*UnsuspendUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UnsuspendUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGlobalChatStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalChatStatsRequest) Reset() {
	*x = GetGlobalChatStatsRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalChatStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalChatStatsRequest) ProtoMessage() {}

func (x *GetGlobalChatStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalChatStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalChatStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

type MessageVolumeStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageVolumeStat) Reset() {
	*x = MessageVolumeStat{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageVolumeStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageVolumeStat) ProtoMessage() {}

func (x *MessageVolumeStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageVolumeStat.ProtoReflect.Descriptor instead.
func (*MessageVolumeStat) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *MessageVolumeStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MessageVolumeStat) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetGlobalChatStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalMessages       int64                  `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	TotalConversations  int64                  `protobuf:"varint,2,opt,name=total_conversations,json=totalConversations,proto3" json:"total_conversations,omitempty"`
	MessageVolumeStats  []*MessageVolumeStat   `protobuf:"bytes,3,rep,name=message_volume_stats,json=messageVolumeStats,proto3" json:"message_volume_stats,omitempty"`
	TotalConnectedUsers int64                  `protobuf:"varint,4,opt,name=total_connected_users,json=totalConnectedUsers,proto3" json:"total_connected_users,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetGlobalChatStatsResponse) Reset() {
	*x = GetGlobalChatStatsResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalChatStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalChatStatsResponse) ProtoMessage() {}

func (x *GetGlobalChatStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalChatStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalChatStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetGlobalChatStatsResponse) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetGlobalChatStatsResponse) GetTotalConversations() int64 {
	if x != nil {
		return x.TotalConversations
	}
	return 0
}

func (x *GetGlobalChatStatsResponse) GetMessageVolumeStats() []*MessageVolumeStat {
	if x != nil {
		return x.MessageVolumeStats
	}
	return nil
}

func (x *GetGlobalChatStatsResponse) GetTotalConnectedUsers() int64 {
	if x != nil {
		return x.TotalConnectedUsers
	}
	return 0
}

type Wallpaper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // numeric ID
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallpaper) Reset() {
	*x = Wallpaper{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallpaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallpaper) ProtoMessage() {}

func (x *Wallpaper) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallpaper.ProtoReflect.Descriptor instead.
func (*Wallpaper) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *Wallpaper) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallpaper) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Wallpaper) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Wallpaper) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SetAppPreferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppPreferenceRequest) Reset() {
	*x = SetAppPreferenceRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppPreferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppPreferenceRequest) ProtoMessage() {}

func (x *SetAppPreferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppPreferenceRequest.ProtoReflect.Descriptor instead.
func (*SetAppPreferenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *SetAppPreferenceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetAppPreferenceRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetAppPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPreferencesRequest) Reset() {
	*x = GetAppPreferencesRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPreferencesRequest) ProtoMessage() {}

func (x *GetAppPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetAppPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetAppPreferencesRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetAppPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preferences   map[string]string      `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppPreferencesResponse) Reset() {
	*x = GetAppPreferencesResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppPreferencesResponse) ProtoMessage() {}

func (x *GetAppPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetAppPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetAppPreferencesResponse) GetPreferences() map[string]string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type AddWallpaperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWallpaperRequest) Reset() {
	*x = AddWallpaperRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWallpaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWallpaperRequest) ProtoMessage() {}

func (x *AddWallpaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWallpaperRequest.ProtoReflect.Descriptor instead.
func (*AddWallpaperRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *AddWallpaperRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteWallpaperRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // numeric ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWallpaperRequest) Reset() {
	*x = DeleteWallpaperRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWallpaperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWallpaperRequest) ProtoMessage() {}

func (x *DeleteWallpaperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWallpaperRequest.ProtoReflect.Descriptor instead.
func (*DeleteWallpaperRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteWallpaperRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWallpapersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWallpapersRequest) Reset() {
	*x = GetWallpapersRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWallpapersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWallpapersRequest) ProtoMessage() {}

func (x *GetWallpapersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWallpapersRequest.ProtoReflect.Descriptor instead.
func (*GetWallpapersRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetWallpapersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type GetWallpapersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallpapers    []*Wallpaper           `protobuf:"bytes,1,rep,name=wallpapers,proto3" json:"wallpapers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWallpapersResponse) Reset() {
	*x = GetWallpapersResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWallpapersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWallpapersResponse) ProtoMessage() {}

func (x *GetWallpapersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWallpapersResponse.ProtoReflect.Descriptor instead.
func (*GetWallpapersResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetWallpapersResponse) GetWallpapers() []*Wallpaper {
	if x != nil {
		return x.Wallpapers
	}
	return nil
}

var File_proto_admin_v1_admin_proto protoreflect.FileDescriptor

const file_proto_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/admin_v1/admin.proto\x12\badmin.v1\"w\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\tR\fstatusFilter\"\x80\x01\n" +
	"\x11ListUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.admin.v1.AdminUserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\"\xa9\x01\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vinserted_at\x18\x06 \x01(\tR\n" +
	"insertedAt\x12\x15\n" +
	"\x06is_kyc\x18\a \x01(\bR\x05isKyc\"a\n" +
	"\x12SuspendUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"/\n" +
	"\x14UnsuspendUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19GetGlobalChatStatsRequest\"=\n" +
	"\x11MessageVolumeStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xf7\x01\n" +
	"\x1aGetGlobalChatStatsResponse\x12%\n" +
	"\x0etotal_messages\x18\x01 \x01(\x03R\rtotalMessages\x12/\n" +
	"\x13total_conversations\x18\x02 \x01(\x03R\x12totalConversations\x12M\n" +
	"\x14message_volume_stats\x18\x03 \x03(\v2\x1b.admin.v1.MessageVolumeStatR\x12messageVolumeStats\x122\n" +
	"\x15total_connected_users\x18\x04 \x01(\x03R\x13totalConnectedUsers\"i\n" +
	"\tWallpaper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"A\n" +
	"\x17SetAppPreferenceRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\x18GetAppPreferencesRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xb3\x01\n" +
	"\x19GetAppPreferencesResponse\x12V\n" +
	"\vpreferences\x18\x01 \x03(\v24.admin.v1.GetAppPreferencesResponse.PreferencesEntryR\vpreferences\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x13AddWallpaperRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"(\n" +
	"\x16DeleteWallpaperRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x14GetWallpapersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\"L\n" +
	"\x15GetWallpapersResponse\x123\n" +
	"\n" +
	"wallpapers\x18\x01 \x03(\v2\x13.admin.v1.WallpaperR\n" +
	"wallpapers2\xdb\x05\n" +
	"\fAdminService\x12D\n" +
	"\tListUsers\x12\x1a.admin.v1.ListUsersRequest\x1a\x1b.admin.v1.ListUsersResponse\x12E\n" +
	"\vSuspendUser\x12\x1c.admin.v1.SuspendUserRequest\x1a\x18.admin.v1.ActionResponse\x12I\n" +
	"\rUnsuspendUser\x12\x1e.admin.v1.UnsuspendUserRequest\x1a\x18.admin.v1.ActionResponse\x12_\n" +
	"\x12GetGlobalChatStats\x12#.admin.v1.GetGlobalChatStatsRequest\x1a$.admin.v1.GetGlobalChatStatsResponse\x12B\n" +
	"\fAddWallpaper\x12\x1d.admin.v1.AddWallpaperRequest\x1a\x13.admin.v1.Wallpaper\x12M\n" +
	"\x0fDeleteWallpaper\x12 .admin.v1.DeleteWallpaperRequest\x1a\x18.admin.v1.ActionResponse\x12P\n" +
	"\rGetWallpapers\x12\x1e.admin.v1.GetWallpapersRequest\x1a\x1f.admin.v1.GetWallpapersResponse\x12O\n" +
	"\x10SetAppPreference\x12!.admin.v1.SetAppPreferenceRequest\x1a\x18.admin.v1.ActionResponse\x12\\\n" +
	"\x11GetAppPreferences\x12\".admin.v1.GetAppPreferencesRequest\x1a#.admin.v1.GetAppPreferencesResponseB6Z4github.com/oririfai/revoluchat-go-sdk/proto/admin_v1b\x06proto3"

var (
	file_proto_admin_v1_admin_proto_rawDescOnce sync.Once
	file_proto_admin_v1_admin_proto_rawDescData []byte
)

func file_proto_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)))
	})
	return file_proto_admin_v1_admin_proto_rawDescData
}

var file_proto_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_admin_v1_admin_proto_goTypes = []any{
	(*ListUsersRequest)(nil),           // 0: admin.v1.ListUsersRequest
	(*ListUsersResponse)(nil),          // 1: admin.v1.ListUsersResponse
	(*AdminUser)(nil),                  // 2: admin.v1.AdminUser
	(*SuspendUserRequest)(nil),         // 3: admin.v1.SuspendUserRequest
	(*UnsuspendUserRequest)(nil),       // 4: admin.v1.UnsuspendUserRequest
	(*ActionResponse)(nil),             // 5: admin.v1.ActionResponse
	(*GetGlobalChatStatsRequest)(nil),  // 6: admin.v1.GetGlobalChatStatsRequest
	(*MessageVolumeStat)(nil),          // 7: admin.v1.MessageVolumeStat
	(*GetGlobalChatStatsResponse)(nil), // 8: admin.v1.GetGlobalChatStatsResponse
	(*Wallpaper)(nil),                  // 9: admin.v1.Wallpaper
	(*SetAppPreferenceRequest)(nil),    // 10: admin.v1.SetAppPreferenceRequest
	(*GetAppPreferencesRequest)(nil),   // 11: admin.v1.GetAppPreferencesRequest
	(*GetAppPreferencesResponse)(nil),  // 12: admin.v1.GetAppPreferencesResponse
	(*AddWallpaperRequest)(nil),        // 13: admin.v1.AddWallpaperRequest
	(*DeleteWallpaperRequest)(nil),     // 14: admin.v1.DeleteWallpaperRequest
	(*GetWallpapersRequest)(nil),       // 15: admin.v1.GetWallpapersRequest
	(*GetWallpapersResponse)(nil),      // 16: admin.v1.GetWallpapersResponse
	nil,                                // 17: admin.v1.GetAppPreferencesResponse.PreferencesEntry
}
var file_proto_admin_v1_admin_proto_depIdxs = []int32{
	2,  // 0: admin.v1.ListUsersResponse.users:type_name -> admin.v1.AdminUser
	7,  // 1: admin.v1.GetGlobalChatStatsResponse.message_volume_stats:type_name -> admin.v1.MessageVolumeStat
	17, // 2: admin.v1.GetAppPreferencesResponse.preferences:type_name -> admin.v1.GetAppPreferencesResponse.PreferencesEntry
	9,  // 3: admin.v1.GetWallpapersResponse.wallpapers:type_name -> admin.v1.Wallpaper
	0,  // 4: admin.v1.AdminService.ListUsers:input_type -> admin.v1.ListUsersRequest
	3,  // 5: admin.v1.AdminService.SuspendUser:input_type -> admin.v1.SuspendUserRequest
	4,  // 6: admin.v1.AdminService.UnsuspendUser:input_type -> admin.v1.UnsuspendUserRequest
	6,  // 7: admin.v1.AdminService.GetGlobalChatStats:input_type -> admin.v1.GetGlobalChatStatsRequest
	13, // 8: admin.v1.AdminService.AddWallpaper:input_type -> admin.v1.AddWallpaperRequest
	14, // 9: admin.v1.AdminService.DeleteWallpaper:input_type -> admin.v1.DeleteWallpaperRequest
	15, // 10: admin.v1.AdminService.GetWallpapers:input_type -> admin.v1.GetWallpapersRequest
	10, // 11: admin.v1.AdminService.SetAppPreference:input_type -> admin.v1.SetAppPreferenceRequest
	11, // 12: admin.v1.AdminService.GetAppPreferences:input_type -> admin.v1.GetAppPreferencesRequest
	1,  // 13: admin.v1.AdminService.ListUsers:output_type -> admin.v1.ListUsersResponse
	5,  // 14: admin.v1.AdminService.SuspendUser:output_type -> admin.v1.ActionResponse
	5,  // 15: admin.v1.AdminService.UnsuspendUser:output_type -> admin.v1.ActionResponse
	8,  // 16: admin.v1.AdminService.GetGlobalChatStats:output_type -> admin.v1.GetGlobalChatStatsResponse
	9,  // 17: admin.v1.AdminService.AddWallpaper:output_type -> admin.v1.Wallpaper
	5,  // 18: admin.v1.AdminService.DeleteWallpaper:output_type -> admin.v1.ActionResponse
	16, // 19: admin.v1.AdminService.GetWallpapers:output_type -> admin.v1.GetWallpapersResponse
	5,  // 20: admin.v1.AdminService.SetAppPreference:output_type -> admin.v1.ActionResponse
	12, // 21: admin.v1.AdminService.GetAppPreferences:output_type -> admin.v1.GetAppPreferencesResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_admin_proto_init() }
func file_proto_admin_v1_admin_proto_init() {
	if File_proto_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_admin_proto = out.File
	file_proto_admin_v1_admin_proto_goTypes = nil
	file_proto_admin_v1_admin_proto_depIdxs = nil
}
